services:

  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bullseye

  tool:
    image: phpmyadmin
    ports:
      - "8085:80"  
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT} 
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_DBNAME=${DB_NAME}