services:

  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bullseye

  marker:
    image: savatar101/marker-api:0.3
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]